# Generated by Django 6.0.1 on 2026-01-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='bg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
